name: CI for Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Lint Frontend Code
        run: npm run lint
        working-directory: ./frontend

      - name: Build Frontend Code
        run: npm run build
        working-directory: ./frontend

      - name: Test Frontend Code
        run: npm test
        working-directory: ./frontend

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Lint Backend Code
        run: npm run lint
        working-directory: ./backend

      - name: Build Backend Code
        run: npm run build
        working-directory: ./backend

      - name: Test Backend Code
        run: npm test
        working-directory: ./backend
